data:
  image: djocker/orodata
source_code:
  image: djocker/marellocommerce
db:
  image: mysql:5.5
  expose:
    - "3306"
  environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=marellocommerce
    - MYSQL_USER=marellocommerce
    - MYSQL_PASSWORD=marellocommerce
  volumes_from:
    - data
mail:
  image: catatnight/postfix
  expose:
    - "25"
  environment:
    - maildomain=localhost
    - smtp_user=marellocommerce@localhost:marellocommerce
minion:
  image: djocker/oromono
  links:
    - "db"
    - "mail"
  ports:
    - "3080:80"
    - "8080:8080"
  volumes_from:
    - data
    - source_code
  environment:
    - CMD_INIT_BEFORE=
    - CMD_INIT_CLEAN=sudo -u www-data -E /usr/bin/php /var/www/app/console oro:install --timeout 3600 --force --drop-database --env=prod --user-name=admin --user-firstname=John --user-lastname=Doe --user-password="admin1111" --user-email="johndoe@example.com" --organization-name="Marello" --application-url="http://localhost/"
    - CMD_INIT_INSTALLED=
    - CMD_INIT_AFTER=
    - APP_DB_DRIVER=pdo_mysql
    - APP_DB_HOST=db
    - APP_DB_PORT=3306
    - APP_DB_USER=marellocommerce
    - APP_DB_PASSWORD=marellocommerce
    - APP_DB_NAME=marellocommerce
    - APP_HOSTNAME=localhost
    - APP_MAILER_TRANSPORT=smtp
    - APP_MAILER_HOST=mail
    - APP_MAILER_PORT=25
    - APP_MAILER_ENCRYPTION=
    - APP_MAILER_USER=marellocommerce
    - APP_MAILER_PASSWORD=marellocommerce
    - APP_WEBSOCKET_BACKEND_PORT=8080  
    - APP_WEBSOCKET_FRONTEND_PORT=8080  
    - APP_SECRET=123456789  
    - APP_IS_INSTALLED=
